;; Color Theme 
(require 'color-theme) 
(color-theme-initialize)
(load-file "~/.emacs.d/vendor/themes/twilight/color-theme-twilight.el")
(load-file "~/.emacs.d/themes/github/color-theme-github.el")
(load-file "~/.emacs.d/themes/irblack/color-theme-ir-black.el")
(load-file "~/.emacs.d/themes/merbivore/color-theme-merbivore.el")
(load-file "~/.emacs.d/themes/tango2/color-theme-tango-2.el")
(load-file "~/.emacs.d/themes/vibrant-ink/color-theme-vibrant-ink.el")
(load-file "~/.emacs.d/themes/inkpot.el")
(color-theme-ir-black)
